add responsive CSS spritesheet generator

diff --git a/apps/cli/livingdex b/apps/cli/livingdex
--- a/apps/cli/livingdex
+++ b/apps/cli/livingdex
@@ -24,14 +24,15 @@ livingdex_usage() {
   echo
   # :command.usage_commands
   printf "Commands:\n"
-  echo "  info      Shows system info"
-  echo "  build     Builds the entire project (DB, assets and UI)"
-  echo "  install   Installs project dependencies"
-  echo "  update    Updates (and upgrades) project dependencies"
-  echo "  clear     Clears cache, dist and other generated files"
-  echo "  deploy    Deploys the current state of the UI build into gh-pages"
-  echo "  query     Queries the db DB and returns the results in JSON format"
-  echo "  megadl    Downloads a file from mega.nz (requires old file URL format)"
+  echo "  info                Shows system info"
+  echo "  build               Builds the entire project (DB, assets and UI)"
+  echo "  install             Installs project dependencies"
+  echo "  update              Updates (and upgrades) project dependencies"
+  echo "  clear               Clears cache, dist and other generated files"
+  echo "  deploy              Deploys the current state of the UI build into gh-pages"
+  echo "  mount-spritesheet   Mounts a responsive CSS spritesheet out of the Pokemon HOME renders"
+  echo "  query               Queries the db DB and returns the results in JSON format"
+  echo "  megadl              Downloads a file from mega.nz (requires old file URL format)"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -255,6 +256,37 @@ livingdex_deploy_usage() {
     printf "Examples:\n"
     
     printf "  ./livingdex deploy\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+livingdex_mount_spritesheet_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "livingdex mount-spritesheet - Mounts a responsive CSS spritesheet out of the Pokemon HOME renders\n"
+    echo 
+  else
+    printf "livingdex mount-spritesheet - Mounts a responsive CSS spritesheet out of the Pokemon HOME renders\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  livingdex mount-spritesheet\n"
+  printf "  livingdex mount-spritesheet --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    
+    printf "  ./livingdex mount-spritesheet\n"
     echo
 
   fi
@@ -1121,7 +1153,7 @@ livingdex_build_command() {
   CSV_DATA_DIR="${DIST_DIR}/csv"
   JSON_DATA_DIR="${DIST_DIR}/json"
   
-  function livingdex_cleanup() {
+  function dist_cleanup() {
     rm -rf "${DIST_DIR}"
     mkdir -p "${CSV_DATA_DIR}"
     mkdir -p "${JSON_DATA_DIR}"
@@ -1150,42 +1182,33 @@ livingdex_build_command() {
     mkdir -p "${UI_ASSETS_DIR}/data/json"
     cp -R "${DIST_DIR}/json" "${UI_ASSETS_DIR}/data"
     # TODO generate pokemon index from DB app and remove this mjs
-    node "${APPS_DIR}/cli/src/build-ui-pokemon-index.mjs"
+    node "${APPS_DIR}/cli/scripts/build-ui-pokemon-index.mjs"
   }
   
   function ui_generate_thumbnails() {
-    THUMBS_DIR="${UI_ASSETS_DIR}/images/home"
+    THUMBS_DIR="${UI_ASSETS_DIR}/images"
   
     if [[ ! -d "${THUMBS_DIR}" ]]; then
-      echo "Adding image assets and generating thumbnails..."
+      mkdir -p "${THUMBS_DIR}"
   
-      HOME_RENDERS_THUMBNAIL_RESIZE=${HOME_RENDERS_THUMBNAIL_RESIZE:-"25%"}
-  
-      rm -rf ${THUMBS_DIR} && mkdir -p ${THUMBS_DIR}
+      "${CLI_APP}" mount-spritesheet
   
       echo "Copying original Pokemon renders to ${THUMBS_DIR} ..."
-  
-      cp -nR "${SOURCES_DIR}/livingdex-renders/images/home/pokemon/" ${THUMBS_DIR}
-      PNG_FILES=$(find "${THUMBS_DIR}" -name "*.png")
-  
-      echo "Resizing Pokemon renders to ${HOME_RENDERS_THUMBNAIL_RESIZE} of size (may take up to 5 min) ..."
-  
-      for f in ${PNG_FILES}; do
-        mogrify -resize "${HOME_RENDERS_THUMBNAIL_RESIZE}" "${f}"
-      done
+      cp -nR "${HOME_RENDERS_DIR}/pokemon-edited/" "${THUMBS_DIR}/pokemon-home"
+      cp -f "${RESOURCES_DIR}/img/placeholder.png" "${THUMBS_DIR}/placeholder.png"
   
       echo "Thumbnails created successfully."
     fi
   }
   
   function livingdex_build() {
-    livingdex_cleanup
+    dist_cleanup
   
     # export pokemon GO data
-    cd "${APPS_DIR}/pogo-dumper" && make
+    # cd "${APPS_DIR}/pogo-dumper" && make
   
     # rebuild DB
-    cd "${APPS_DIR}/db" && make
+    # cd "${APPS_DIR}/db" && make
   
     # export data from DB
     table_export_csv_all
@@ -1280,6 +1303,54 @@ livingdex_deploy_command() {
   
   rm -rf public/assets/data/csv public/assets/data/pogo
   npm run deploy
+}
+
+# :command.function
+livingdex_mount_spritesheet_command() {
+  # :src/mount_spritesheet_command.sh
+  
+  cd "${HOME_RENDERS_DIR}"
+  
+  if [[ ! -d ./pokemon-edited ]]; then
+    echo "Resizing PNGS to ${HOME_RENDERS_THUMBNAIL_RESIZE} ..."
+    cp -R pokemon pokemon-edited
+    mogrify -resize "${HOME_RENDERS_THUMBNAIL_RESIZE}" pokemon-edited/*.png
+    mogrify -resize "${HOME_RENDERS_THUMBNAIL_RESIZE}" pokemon-edited/regular/*.png
+    mogrify -resize "${HOME_RENDERS_THUMBNAIL_RESIZE}" pokemon-edited/shiny/*.png
+  fi
+  
+  cd pokemon-edited
+  
+  # montage regular/*.png -tile 4x2 -geometry 512x512+0+0 -background transparent pokemon-regular.png
+  # montage regular/00*.png -geometry 512x512+0+0 -background transparent -border 2 -bordercolor transparent pokemon-regular.png
+  
+  function mount_spritesheet() {
+    montage "${1}"/*.png \
+      -tile 32x48 \
+      -background transparent \
+      -border 2 \
+      -bordercolor transparent \
+      -interlace line \
+      "${2}"
+  #  montage "${1}"/*.png \
+  #    -tile 32x48 \
+  #    -background transparent \
+  #    "${2}"
+  }
+  
+  if [[ ! -f "./pokemon-regular.png" ||  ! -f "./pokemon-shiny.png" ]]; then
+    echo "Mounting HOME renders spritesheet PNG and CSS..."
+    mount_spritesheet regular pokemon-regular.png
+    mount_spritesheet shiny pokemon-shiny.png
+  
+    echo "Optimizing PNGs..."
+    optipng pokemon-regular.png
+    optipng pokemon-shiny.png
+  fi
+  
+  php "${APPS_DIR}/cli/scripts/generate-spritesheet-css.php"
+  
+  echo "Responsive CSS spritesheet generated."
 }
 
 # :command.function
@@ -1388,6 +1459,13 @@ parse_requirements() {
     action="deploy"
     shift
     livingdex_deploy_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  mount-spritesheet )
+    action="mount-spritesheet"
+    shift
+    livingdex_mount_spritesheet_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -1714,6 +1792,51 @@ livingdex_deploy_parse_requirements() {
 }
 
 # :command.parse_requirements
+livingdex_mount_spritesheet_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    livingdex_mount_spritesheet_usage
+    exit
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="mount-spritesheet"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+  
+    esac
+  done
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
+# :command.parse_requirements
 livingdex_query_parse_requirements() {
   # :command.fixed_flag_filter
   case "$1" in
@@ -1912,6 +2035,14 @@ run() {
       livingdex_deploy_usage
     else
       livingdex_deploy_command
+    fi
+  
+  elif [[ $action == "mount-spritesheet" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      livingdex_mount_spritesheet_usage
+    else
+      livingdex_mount_spritesheet_command
     fi
   
   elif [[ $action == "query" ]]; then
